[project]
name = "silx-datastructs-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0",
    "pydantic>=2.9.2",
    "scipy>=1.14.1",
]
